Prevent execution of functions except the explicitly granted ones
The functions are owned by the "pci" and "nonpci" groups,
and since a member of a group can executed any functions owned by the
same group, the "www-data" user cannot be a member of the same groups.

Therefore, two new groups have been added, "pci_api" and "nonpci_api",
which only have execute permissions to the API-functions and nothing else.

Also, since the HTTP_Post_XML() function must be created by a SUPERUSER
since it's a plperlu function, also explicitly revoke execute rights
to the function to prevent any user to execute it except from the
SECURITY DEFINER functions that executes as "pci" and "nonpci".

Example:

Joels-MacBook-Pro:pci-blackbox joel$ psql -U "www-data" nonpci
Pager is always used.
psql (9.1.15)
Type "help" for help.

pg1:nonpci=> select HTTP_POST_XML('','','','<xml></xml>'::xml);
ERROR:  permission denied for function http_post_xml
pg1:nonpci=>* \q
Joels-MacBook-Pro:pci-blackbox joel$ psql -U "www-data" pci
Pager is always used.
psql (9.1.15)
Type "help" for help.

pg1:pci=> select HTTP_POST_XML('','','','<xml></xml>'::xml);
ERROR:  permission denied for function http_post_xml
pg1:pci=>* \q